name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"

      - name: Install dependencies
        run: yarn

      - name: Build (with tsc)
        run: yarn tsc --noEmit

      - name: Build (with serverless and esbuild)
        run: yarn sls package